<a href="https://colab.research.google.com/github/narinderthakur01-cyber/PYTHON_PREP-PROJECTS_/blob/main/Day3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy.random import randint as ri
import pandas as pd
tab=np.array(ri(1,5,9)).reshape(3,3)
tab
col=['A','B','C']
row=['X','Y','Z']
tab.ndim
df=pd.DataFrame(data=tab,index=row,columns=col)

In [ ]:
import numpy as np
from numpy.random import randint as ri
import pandas as pd

# Generate 64 random integers from 1 to 6
# Reshape them into an 8x8 NumPy array
tb = np.array(ri(1, 7, 64)).reshape(8, 8)
print(tb)

# Define column names
col = ['X', 'Y', 'Z', 'N', 'M', 'O', 'P', 'R']

# Define row/index names
row = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

# Create DataFrame using custom row and column labels
df = pd.DataFrame(
    data=tb,
    index=row,
    columns=col
)

print(df)
print("-" * 50)


# Drop row 'A'
# By default, drop() removes rows because axis=0
# This does not permanently modify df unless inplace=True is used
print(df.drop('A'))

# To permanently remove row 'A':
# df.drop('A', axis=0, inplace=True)

# To remove column 'O':
# df.drop('O', axis=1, inplace=True)

print("-" * 50)


# Select rows using integer positions
# iloc[0:3] selects rows at positions 0, 1, and 2
print(df.iloc[0:3])
print("-" * 50)


# Select all rows and column at position 2
# Column position 2 is 'Z'
print(df.iloc[:, 2])
print("-" * 50)


# Select the value at row position 1 and column position 2
print(df.iloc[1, 2])
print("-" * 50)


# Select specific rows and columns by integer positions
# Rows: positions 1 and 3
# Columns: positions 3 and 6
print(df.iloc[[1, 3], [3, 6]])
print("-" * 50)


# Multiply every numerical value in the DataFrame by 6
df = df * 6

# Create a Boolean DataFrame
# True where the value is greater than 20
print(df > 20)

# Store the Boolean condition in bdf
bdf = df > 31

# Display only values where condition is True
# Other values become NaN
print(df[bdf])
print("-" * 50)

print(bdf)
print("-" * 50)

print(df)


# Correct filtering:
# 'A' is a row label, not a column name.
# Use row filtering with index labels through loc.

# Select row 'A' and check values greater than 15
print(df.loc["A"] > 15)

# Select rows where column 'O' is greater than 89
print(df[df["O"] > 89])

# Select rows where column 'O' is greater than 89
# and row index is not directly used as a column condition

[[6 5 6 2 1 2 4 5]
 [2 3 6 6 3 3 6 5]
 [1 4 6 6 4 1 4 1]
 [5 1 3 6 6 2 2 2]
 [2 4 6 6 3 5 3 3]
 [5 4 1 5 2 4 6 3]
 [6 4 4 1 3 1 1 5]
 [6 3 4 2 2 1 1 4]]
   X  Y  Z  N  M  O  P  R
A  6  5  6  2  1  2  4  5
B  2  3  6  6  3  3  6  5
C  1  4  6  6  4  1  4  1
D  5  1  3  6  6  2  2  2
E  2  4  6  6  3  5  3  3
F  5  4  1  5  2  4  6  3
G  6  4  4  1  3  1  1  5
H  6  3  4  2  2  1  1  4
--------------------------------------------------
   X  Y  Z  N  M  O  P  R
B  2  3  6  6  3  3  6  5
C  1  4  6  6  4  1  4  1
D  5  1  3  6  6  2  2  2
E  2  4  6  6  3  5  3  3
F  5  4  1  5  2  4  6  3
G  6  4  4  1  3  1  1  5
H  6  3  4  2  2  1  1  4
--------------------------------------------------
   X  Y  Z  N  M  O  P  R
A  6  5  6  2  1  2  4  5
B  2  3  6  6  3  3  6  5
C  1  4  6  6  4  1  4  1
--------------------------------------------------
A    6
B    6
C    6
D    3
E    6
F    1
G    4
H    4
Name: Z, dtype: int64
--------------------------------------------------
6
--------------------------------------------------
   N  P
B  6  6
D  6  2
--------------------------------------------------
       X      Y      Z      N      M      O      P      R
A   True   True   True  False  False  False   True   True
B  False  False   True   True  False  False   True   True
C  False   True   True   True   True  False   True  False
D   True  False  False   True   True  False  False  False
E  False   True   True   True  False   True  False  False
F   True   True  False   True  False   True   True  False
G   True   True   True  False  False  False  False   True
H   True  False   True  False  False  False  False   True
      X   Y     Z     N     M   O     P   R
A  36.0 NaN  36.0   NaN   NaN NaN   NaN NaN
B   NaN NaN  36.0  36.0   NaN NaN  36.0 NaN
C   NaN NaN  36.0  36.0   NaN NaN   NaN NaN
D   NaN NaN   NaN  36.0  36.0 NaN   NaN NaN
E   NaN NaN  36.0  36.0   NaN NaN   NaN NaN
F   NaN NaN   NaN   NaN   NaN NaN  36.0 NaN
G  36.0 NaN   NaN   NaN   NaN NaN   NaN NaN
H  36.0 NaN   NaN   NaN   NaN NaN   NaN NaN
--------------------------------------------------
       X      Y      Z      N      M      O      P      R
A   True  False   True  False  False  False  False  False
B  False  False   True   True  False  False   True  False
C  False  False   True   True  False  False  False  False
D  False  False  False   True   True  False  False  False
E  False  False   True   True  False  False  False  False
F  False  False  False  False  False  False   True  False
G   True  False  False  False  False  False  False  False
H   True  False  False  False  False  False  False  False
--------------------------------------------------
    X   Y   Z   N   M   O   P   R
A  36  30  36  12   6  12  24  30
B  12  18  36  36  18  18  36  30
C   6  24  36  36  24   6  24   6
D  30   6  18  36  36  12  12  12
E  12  24  36  36  18  30  18  18
F  30  24   6  30  12  24  36  18
G  36  24  24   6  18   6   6  30
H  36  18  24  12  12   6   6  24
X     True
Y     True
Z     True
N    False
M    False
O    False
P     True
R     True
Name: A, dtype: bool
Empty DataFrame
Columns: [X, Y, Z, N, M, O, P, R]
Index: []

In [ ]:
#for Numpy
import numpy as np
from numpy.random import randint as ri
num=np.arange(1,21)
print(num)
print("-"*100)
print(num.ndim)
print("-"*100)
print(num.size)
print("-"*100)
print(type(num)," ",num.dtype)
num1=np.array(ri(1, 6,24)).reshape(4,6)
print("-"*100)
print(num1,"\n",num1.ndim,num1.size,num1.shape)
print("-"*100)
print(num1.reshape(2,3,4))
print("-"*100)
arr = np.arange(1, 21).reshape(4, 5)
print("-"*100)
print(arr)
print("-"*100)
print(arr[0:1,:])
print("-"*100)
print(arr[:,4])
print("-"*100)
print(arr[1:3,])
print("-"*100)
print(arr[1:3,1:4])
print("-"*100)
print(arr[:,::-1])
print("-"*100)
print(arr[::-1,:])
print("-"*100)
arr1 = np.array([2, 4, 6, 8, 10])
print(arr1**2)
print("-"*100)
print(arr1+5)
print("-"*100)
print(arr1*3)
print("-"*100)
print(np.std(arr1)," ",np.mean(arr1))
arr2 = np.array([12, 5, 8, 21, 3, 18, 7, 30])
print("-"*100)
print(arr2[arr2>10])
print("-"*100)
print(arr2[arr2%2==0])
print("-"*100)
print(arr2[(arr2>=5 )& (arr2<=20)])
print("-"*100)
arr3 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(np.sum(arr3))
print("-"*100)
print(np.sum(arr3,axis=1))
print("-"*100)
print(np.sum(arr3,axis=0))
print("-"*100)
print(np.max(arr3,axis=1))
print("-"*100)
print(np.min(arr3,axis=0))
print("-"*100)
arr4=ri(1,100,20)
print(arr4)
print("-"*100)
print(np.sort(arr4))
print("-"*100)
print(np.unique(arr4))
print("-"*100)
print(arr4.max(),arr4.min())
print("-"*100)
arr4=np.array(arr4).reshape(4,5)
print(arr4)
arr5= np.array([
    [10, 20, 30],
    [40, 50, 60]
])
arrn=[1,2,3]
print("-"*100)
print(arr5+np.array(arrn))
arrc=[10, 100, 1000]
print(arr5*np.array(arrc))
m=np.array(ri(1,5,4)).reshape(2,2)
n=np.array(ri(1,5,4)).reshape(2,2)
print(m+n)
print("-"*100)
print(m*n)
print("-"*100)
print(m@n)
g=m@n
print(g.T)
print("-"*100)
print(np.linalg.det(g))
print("-"*100)

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Aman", "Riya", "Karan", "Simran", "Arjun", "Neha", "Vikram", "Isha"],
    "Age": [21, 22, 20, 23, 21, 22, 24, 20],
    "City": ["Delhi", "Mumbai", "Delhi", "Chandigarh", "Mumbai", "Delhi", "Chandigarh", "Mumbai"],
    "Marks": [85, 72, 90, 66, 78, 95, 58, 88],
    "Department": ["CSE", "IT", "CSE", "ECE", "IT", "CSE", "ECE", "CSE"]
}

df = pd.DataFrame(data)
print(df.head())
print("*"*60)
print(df.tail(3))
print("*"*60)
print(df.shape)
print(df.columns)
print("*"*60)
print(df.index)
print("*"*60)
print(df.dtypes)
print("*"*60)
print(df.info())
print("*"*60)
print(df.describe())
print("*"*60)
print(df["Name"])
print("*"*60)
print(df["Marks"])
print("*"*60)
print(df[["Name","Marks"]])
print("*"*60)
print(df[["Age","City","Department"]])
print("*"*60)
print(df.iloc[0])
print("*"*60)
print(df.iloc[-1,:])
print("*"*60)
print(df.iloc[0:3,:])
print("*"*60)
print(df.iloc[1:5,:])
print("*"*60)
print(df[(df["Marks"]>80)])
print("*"*60)
print(df[(df["Age"]>22)])
print("*"*60)
print(df[(df["City"]=="Delhi")])
print("*"*60)
print(df[(df["Department"]=="CSE")])
print("*"*60)
print(df[(df["Marks"]>22)])
print("*"*60)
print(df[(df["Marks"]>70) &(df["Marks"]<=90)])

print("*"*60)
print(df.loc[2])
print("*"*60)
print(df.loc[1:4])
print(df.loc[2:5, ["Name", "Marks"]])
print(df.loc[df["Department"] == "CSE", ["Name", "Marks"]])
df.loc[df["Name"] == "Karan", "Marks"] = 95

print(df)

df.loc[2, "Marks"] = 95

In [7]:
import pandas as pd
import numpy as np
ab={
    'A':["Narinder",21,"AI Eng", "IND"],
    'B':["Maninder",21,"ML Eng", "ENG"],
    'C':["Sukhinder",20,"CS Eng", "US"]
}
df=pd.DataFrame(ab)
df['D']=["Name","Age","Job","Country"]
df=df.set_index('D')
df

                A         B          C
D
Name     Narinder  Maninder  Sukhinder
Age            21        21         20
Job        AI Eng    ML Eng     CS Eng
Country       IND       ENG         US

In [25]:
import pandas as pd
import numpy as np
d={
    'a':[1,2,np.nan,3],
    'b':[7,6,np.nan,np.nan],
    'c':[90,np.nan,np.nan,np.nan]
}
df=pd.DataFrame(d)
print(df)
print(df.isna())
print(df.notna())
df.dropna(axis=1,thresh=2)
df.fillna(value=df['a'].mean())
df['c']=df['c'].astype('category')
df.info()

     a    b     c
0  1.0  7.0  90.0
1  2.0  6.0   NaN
2  NaN  NaN   NaN
3  3.0  NaN   NaN
       a      b      c
0  False  False  False
1  False  False   True
2   True   True   True
3  False   True   True
       a      b      c
0   True   True   True
1   True   True  False
2  False  False  False
3   True  False  False
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      float64
 1   b       2 non-null      float64
 2   c       1 non-null      category
dtypes: category(1), float64(2)
memory usage: 316.0 bytes

In [28]:
import pandas as pd
import numpy as np

data = {
    "EmployeeID": [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,116,117,118,119,120],

    "Name": ["Aman","Riya","Karan","Simran","Arjun","Neha","Vikram","Isha",
             "Rahul","Priya","Ankit","Mehak","Rohit","Kavya","Sahil","Ananya",
             "Varun","Sneha","Mohit","Tanya"],

    "Age": [22,24,23,26,25,27,29,23,31,28,22,26,30,24,27,25,32,29,23,28],

    "Gender": ["M","F","M","F","M","F","M","F","M","F",
               "M","F","M","F","M","F","M","F","M","F"],

    "Department": ["IT","HR","IT","Finance","IT","HR","Finance","IT",
                   "Finance","HR","IT","Finance","IT","HR","Finance",
                   "IT","Finance","HR","IT","Finance"],

    "City": ["Delhi","Mumbai","Delhi","Chandigarh","Mumbai","Delhi",
             "Chandigarh","Mumbai","Delhi","Chandigarh","Delhi","Mumbai",
             "Chandigarh","Delhi","Mumbai","Delhi","Chandigarh","Mumbai",
             "Delhi","Chandigarh"],

    "Experience": [1,3,2,5,4,6,7,2,8,5,1,4,9,3,6,2,10,7,2,5],

    "Salary": [35000,42000,38000,60000,52000,48000,75000,40000,85000,55000,
               36000,65000,90000,45000,70000,41000,95000,58000,39000,68000],

    "PerformanceScore": [7,8,6,9,8,7,9,6,10,8,7,9,9,7,8,6,10,8,7,9],

    "ProjectsCompleted": [2,4,3,7,5,6,8,3,10,6,2,7,11,4,8,3,12,7,2,9]
}

df = pd.DataFrame(data)
df
mm

Department
Finance    74000.0
HR         49600.0
IT         46375.0
Name: Salary, dtype: float64

In [29]:
import pandas as pd

students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104, 105],
    "Name": ["Aman", "Riya", "Karan", "Simran", "Arjun"],
    "Department": ["CSE", "IT", "CSE", "ECE", "IT"]
})

print(students)
marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 106, 107],
    "Marks": [85, 92, 78, 88, 95],
    "Grade": ["A", "A+", "B", "A", "A+"]
})

print(marks)

   StudentID    Name Department
0        101    Aman        CSE
1        102    Riya         IT
2        103   Karan        CSE
3        104  Simran        ECE
4        105   Arjun         IT
   StudentID  Marks Grade
0        101     85     A
1        102     92    A+
2        103     78     B
3        106     88     A
4        107     95    A+

In [12]:
import pandas as pd

students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104, 105],
    "Name": ["Aman", "Riya", "Karan", "Simran", "Arjun"],
    "Department": ["CSE", "IT", "CSE", "ECE", "IT"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 106, 107],
    "Marks": [85, 92, 78, 88, 95],
    "Grade": ["A", "A+", "B", "A", "A+"]
})

r=pd.merge(students,marks,how='inner')
print(r)
rl=pd.merge(students,marks,on="StudentID",how='left')
print(rl)
rr=pd.merge(students,marks,on="StudentID",how='right')
print(rr)
ro=pd.merge(students,marks,on="StudentID",how='outer')
print(ro)

   StudentID   Name Department  Marks Grade
0        101   Aman        CSE     85     A
1        102   Riya         IT     92    A+
2        103  Karan        CSE     78     B
   StudentID    Name Department  Marks Grade
0        101    Aman        CSE   85.0     A
1        102    Riya         IT   92.0    A+
2        103   Karan        CSE   78.0     B
3        104  Simran        ECE    NaN   NaN
4        105   Arjun         IT    NaN   NaN
   StudentID   Name Department  Marks Grade
0        101   Aman        CSE     85     A
1        102   Riya         IT     92    A+
2        103  Karan        CSE     78     B
3        106    NaN        NaN     88     A
4        107    NaN        NaN     95    A+
   StudentID    Name Department  Marks Grade
0        101    Aman        CSE   85.0     A
1        102    Riya         IT   92.0    A+
2        103   Karan        CSE   78.0     B
3        104  Simran        ECE    NaN   NaN
4        105   Arjun         IT    NaN   NaN
5        106     NaN        NaN   88.0     A
6        107     NaN        NaN   95.0    A+

In [37]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Karan", "Simran", "Arjun", "Neha", "Rahul", "Priya"],
    "Age": [21, 22, 20, 23, 21, 22, 24, 20],
    "Department": ["CSE", "IT", "CSE", "ECE", "IT", "CSE", "ECE", "IT"],
    "Marks": [85, 72, 91, 64, 78, 95, 58, 88],
    "Salary": [45000, 52000, 60000, 40000, 55000, 70000, 35000, 62000],
    "Experience": [1, 2, 3, 1, 2, 4, 1, 3]
}

df = pd.DataFrame(data)
print(df)
def func(x):
 return  x.lower()

df["Department"]=df["Department"].apply(func)
print(df)

     Name  Age Department  Marks  Salary  Experience
0    Aman   21        CSE     85   45000           1
1    Riya   22         IT     72   52000           2
2   Karan   20        CSE     91   60000           3
3  Simran   23        ECE     64   40000           1
4   Arjun   21         IT     78   55000           2
5    Neha   22        CSE     95   70000           4
6   Rahul   24        ECE     58   35000           1
7   Priya   20         IT     88   62000           3
     Name  Age Department  Marks  Salary  Experience
0    Aman   21        cse     85   45000           1
1    Riya   22         it     72   52000           2
2   Karan   20        cse     91   60000           3
3  Simran   23        ece     64   40000           1
4   Arjun   21         it     78   55000           2
5    Neha   22        cse     95   70000           4
6   Rahul   24        ece     58   35000           1
7   Priya   20         it     88   62000           3

In [63]:
import pandas as pd
import math
data = {
    "Name": ["Aman", "Riya", "Karan", "Simran", "Arjun", "Neha", "Rahul", "Priya"],
    "Age": [21, 22, 20, 23, 21, 22, 24, 20],
    "Department": ["CSE", "IT", "CSE", "ECE", "IT", "CSE", "ECE", "IT"],
    "Marks": [85, 72, 91, 64, 78, 95, 58, 88],
    "Salary": [45000, 52000, 60000, 40000, 55000, 70000, 35000, 62000],
    "Experience": [1, 2, 3, 1, 2, 4, 1, 3]
}

df = pd.DataFrame(data)
# print(df)
# def funcq(x):
#   return x*x

# df["DoubleMarks"]=df["Marks"].apply(funcq)
# df
def pas(x):
  if x>45:
    return "pass"
  else:
    return "fail"
df["PassStatus"]=df["Marks"].apply(pas)
print(df)

def grad(x):
  if x>=90:
    return "A+"
  elif x>=80 :
    return "A"
  elif x>=70 :
    return "B"
  elif x>=60 :
    return "C"
  else:
    return "D"
df["Grade"]=df["Marks"].apply(grad)
print(df)
df["NameLen"]=df["Name"].apply(len)
df
df["Salarysqrt"]=df["Salary"].apply(math.sqrt)
df

     Name  Age Department  Marks  Salary  Experience PassStatus
0    Aman   21        CSE     85   45000           1       pass
1    Riya   22         IT     72   52000           2       pass
2   Karan   20        CSE     91   60000           3       pass
3  Simran   23        ECE     64   40000           1       pass
4   Arjun   21         IT     78   55000           2       pass
5    Neha   22        CSE     95   70000           4       pass
6   Rahul   24        ECE     58   35000           1       pass
7   Priya   20         IT     88   62000           3       pass
     Name  Age Department  Marks  Salary  Experience PassStatus Grade
0    Aman   21        CSE     85   45000           1       pass     A
1    Riya   22         IT     72   52000           2       pass     B
2   Karan   20        CSE     91   60000           3       pass    A+
3  Simran   23        ECE     64   40000           1       pass     C
4   Arjun   21         IT     78   55000           2       pass     B
5    Neha   22        CSE     95   70000           4       pass    A+
6   Rahul   24        ECE     58   35000           1       pass     D
7   Priya   20         IT     88   62000           3       pass     A

,Name,Age,Department,Marks,Salary,Experience,PassStatus,Grade,NameLen,Salarysqrt
0,Aman,21,CSE,85,45000,1,pass,A,4,212.132034
1,Riya,22,IT,72,52000,2,pass,B,4,228.035085
2,Karan,20,CSE,91,60000,3,pass,A+,5,244.948974
3,Simran,23,ECE,64,40000,1,pass,C,6,200.000000
4,Arjun,21,IT,78,55000,2,pass,B,5,234.520788
5,Neha,22,CSE,95,70000,4,pass,A+,4,264.575131
6,Rahul,24,ECE,58,35000,1,pass,D,5,187.082869
7,Priya,20,IT,88,62000,3,pass,A,5,248.997992