<a href="https://colab.research.google.com/github/narinderthakur01-cyber/PYTHON_PREP-PROJECTS_/blob/main/Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import numpy as np
import pandas as pd

data = {
    "Department": [
        "CSE", "CSE", "CSE",
        "IT", "IT", "IT",
        "ECE", "ECE", "ECE"
    ],

    "Year": [
        2024, 2024, 2025,
        2024, 2025, 2025,
        2024, 2024, 2025
    ],

    "StudentID": [
        101, 102, 103,
        104, 105, 106,
        107, 108, 109
    ],

    "Name": [
        "Aman", "Riya", "Karan",
        "Simran", "Arjun", "Neha",
        "Rahul", "Priya", "Vikas"
    ],

    "Age": [
        21, 22, 20,
        23, 21, 22,
        24, 20, 23
    ],

    "Marks": [
        85, 92, 78,
        88, 76, 95,
        67, 81, 90
    ],

    "Salary": [
        45000, 52000, 48000,
        55000, 60000, 65000,
        40000, 47000, 58000
    ],

    "Experience": [
        1, 2, 1,
        2, 3, 4,
        1, 2, 3
    ]
}

df = pd.DataFrame(data)
print(df)
df=df.set_index(["Department","Year"])
print(df)
# df=df.loc["CSE"]
# df
d=df.xs("ECE",level="Department")
d

  Department  Year  StudentID    Name  Age  Marks  Salary  Experience
0        CSE  2024        101    Aman   21     85   45000           1
1        CSE  2024        102    Riya   22     92   52000           2
2        CSE  2025        103   Karan   20     78   48000           1
3         IT  2024        104  Simran   23     88   55000           2
4         IT  2025        105   Arjun   21     76   60000           3
5         IT  2025        106    Neha   22     95   65000           4
6        ECE  2024        107   Rahul   24     67   40000           1
7        ECE  2024        108   Priya   20     81   47000           2
8        ECE  2025        109   Vikas   23     90   58000           3
                 StudentID    Name  Age  Marks  Salary  Experience
Department Year
CSE        2024        101    Aman   21     85   45000           1
           2024        102    Riya   22     92   52000           2
           2025        103   Karan   20     78   48000           1
IT         2024        104  Simran   23     88   55000           2
           2025        105   Arjun   21     76   60000           3
           2025        106    Neha   22     95   65000           4
ECE        2024        107   Rahul   24     67   40000           1
           2024        108   Priya   20     81   47000           2
           2025        109   Vikas   23     90   58000           3

      StudentID   Name  Age  Marks  Salary  Experience
Year
2024        107  Rahul   24     67   40000           1
2024        108  Priya   20     81   47000           2
2025        109  Vikas   23     90   58000           3

In [56]:
import pandas as pd

data = {
    "Department": [
        "CSE", "CSE", "CSE", "CSE",
        "IT", "IT", "IT", "IT",
        "ECE", "ECE", "ECE",
        "ME", "ME", "ME",
        "CSE"
    ],

    "Year": [
        2024, 2024, 2025, 2026,
        2024, 2025, 2025, 2026,
        2024, 2025, 2026,
        2024, 2025, 2026,
        2026
    ],

    "StudentID": [
        101, 102, 103, 104,
        105, 106, 107, 108,
        109, 110, 111,
        112, 113, 114,
        115
    ],

    "Name": [
        "Aman", "Riya", "Karan", "Simran",
        "Arjun", "Neha", "Rahul", "Priya",
        "Vikas", "Anjali", "Rohit",
        "Manav", "Pooja", "Sahil",
        "Nitin"
    ],

    "Age": [
        21, 22, 20, 23,
        21, 22, 24, 20,
        23, 21, 22,
        24, 20, 23,
        22
    ],

    "Marks": [
        85, 92, 78, 88,
        76, 95, 82, 69,
        67, 81, 90,
        74, 86, 79,
        93
    ],

    "Salary": [
        45000, 52000, 48000, 55000,
        60000, 65000, 58000, 50000,
        40000, 47000, 58000,
        42000, 51000, 57000,
        68000
    ],

    "Experience": [
        1, 2, 1, 2,
        3, 4, 2, 1,
        1, 2, 3,
        1, 3, 2,
        4
    ]
}

df = pd.DataFrame(data)

print(df)
df=df.set_index(["Department","Year","StudentID"])
print(df)
print(df.loc["CSE"])
print(df.loc[("CSE",2024)])
print(df.loc[(slice(None),2025),:])
print(df.loc[("IT",2025),:])
r=df.loc[(("CSE","IT"),slice(None)),:]
r
d=df.loc[(slice(None),[2024,2026]),:]
d
t=df.loc[() ]

   Department  Year  StudentID    Name  Age  Marks  Salary  Experience
0         CSE  2024        101    Aman   21     85   45000           1
1         CSE  2024        102    Riya   22     92   52000           2
2         CSE  2025        103   Karan   20     78   48000           1
3         CSE  2026        104  Simran   23     88   55000           2
4          IT  2024        105   Arjun   21     76   60000           3
5          IT  2025        106    Neha   22     95   65000           4
6          IT  2025        107   Rahul   24     82   58000           2
7          IT  2026        108   Priya   20     69   50000           1
8         ECE  2024        109   Vikas   23     67   40000           1
9         ECE  2025        110  Anjali   21     81   47000           2
10        ECE  2026        111   Rohit   22     90   58000           3
11         ME  2024        112   Manav   24     74   42000           1
12         ME  2025        113   Pooja   20     86   51000           3
13         ME  2026        114   Sahil   23     79   57000           2
14        CSE  2026        115   Nitin   22     93   68000           4
                             Name  Age  Marks  Salary  Experience
Department Year StudentID
CSE        2024 101          Aman   21     85   45000           1
                102          Riya   22     92   52000           2
           2025 103         Karan   20     78   48000           1
           2026 104        Simran   23     88   55000           2
IT         2024 105         Arjun   21     76   60000           3
           2025 106          Neha   22     95   65000           4
                107         Rahul   24     82   58000           2
           2026 108         Priya   20     69   50000           1
ECE        2024 109         Vikas   23     67   40000           1
           2025 110        Anjali   21     81   47000           2
           2026 111         Rohit   22     90   58000           3
ME         2024 112         Manav   24     74   42000           1
           2025 113         Pooja   20     86   51000           3
           2026 114         Sahil   23     79   57000           2
CSE        2026 115         Nitin   22     93   68000           4
                  Name  Age  Marks  Salary  Experience
Year StudentID
2024 101          Aman   21     85   45000           1
     102          Riya   22     92   52000           2
2025 103         Karan   20     78   48000           1
2026 104        Simran   23     88   55000           2
     115         Nitin   22     93   68000           4
           Name  Age  Marks  Salary  Experience
StudentID
101        Aman   21     85   45000           1
102        Riya   22     92   52000           2
                             Name  Age  Marks  Salary  Experience
Department Year StudentID
CSE        2025 103         Karan   20     78   48000           1
IT         2025 106          Neha   22     95   65000           4
                107         Rahul   24     82   58000           2
ECE        2025 110        Anjali   21     81   47000           2
ME         2025 113         Pooja   20     86   51000           3
            Name  Age  Marks  Salary  Experience
StudentID
106         Neha   22     95   65000           4
107        Rahul   24     82   58000           2

/tmp/ipykernel_2013/1106983941.py:75: PerformanceWarning: indexing past lexsort depth may impact performance.
  print(df.loc[("CSE",2024)])
/tmp/ipykernel_2013/1106983941.py:77: PerformanceWarning: indexing past lexsort depth may impact performance.
  print(df.loc[("IT",2025),:])

                             Name  Age  Marks  Salary  Experience
Department Year StudentID
CSE        2024 101          Aman   21     85   45000           1
                102          Riya   22     92   52000           2
IT         2024 105         Arjun   21     76   60000           3
ECE        2024 109         Vikas   23     67   40000           1
ME         2024 112         Manav   24     74   42000           1
CSE        2026 104        Simran   23     88   55000           2
IT         2026 108         Priya   20     69   50000           1
ECE        2026 111         Rohit   22     90   58000           3
ME         2026 114         Sahil   23     79   57000           2
CSE        2026 115         Nitin   22     93   68000           4